server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootBlog?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: exia
    password: exia

  thymeleaf:
    cache: false
    encoding: UTF-8


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

